#!/bin/bash
#PBS -N gh_merge_csv
#PBS -l nodes=1:ppn=32:gpus=1
#PBS -l walltime=04:00:00
#PBS -j oe
#PBS -q lab_gpu

# set envirenment
source /public/software/profile.d/cuda10.0.sh
source /public/software/profile.d/python3.sh
conda activate py36

# working
cd /public/home/hengyi/guohong/MLP_RO_2022_10_08/code/data_preprocessing/
python3 ./merge_csv_from_all_734_u_according_to_split_set_in_2021_10_29.py
