#!/bin/bash
#PBS -N gh_merge
#PBS -l nodes=1:ppn=32:gpus=1
#PBS -l walltime=05:00:00
#PBS -j oe
#PBS -q lab_gpu

# set envirenment
source /public/software/profile.d/cuda10.0.sh
source /public/software/profile.d/python3.sh
conda activate py36

# working
cd /public/home/hengyi/guohong/MLP_RO_2022_10_15/code/data_preprocessing/
python3 ./set_split_in_2022_10_15_and_merge_csv_with_doing_single_minmax_xyz_from_all_726_in_734_csv.py
